### ISSUE TITLE
Step3b: Spending password to EncryptedPass

### ISSUE THREAD

**Issue by bazooka70** [ilap/cwag#3]
First, thanks for sharing the code! I learned a lot from it.

However I can't understand where the `EncryptedPass` (Step3b) is used later. 
I didn't even find traces of it on the IO.HK sources (I'm far from being  a Haskel expert, so I might have missed it)

I also looked here and no Scrypt used there:
https://github.com/safeada/python-cardano

If it is there in your code only for the future, Can you please consider to show how to implement a password protected Wallets?

Cheers :)

**Comment by ilap** [comment]
Hi,

It just simply encrypts the secret key see [cardano-crypto's cbits](https://github.com/input-output-hk/cardano-crypto/blob/master/cbits/encrypted_sign.c), and it's used, to decrypt the SK when you sign a transaction or when you need the encrypted SK for some reason. For example, when you create a new account in the wallet.

**Comment by bazooka70** [comment]
Hi, where in the cbits they use `Scrypt` like you did? 
I can only see `ChaCha` and `cryptonite_fastpbkdf2_hmac_sha512`. is the `cryptonite_fastpbkdf2_hmac_sha512` implemented via `Scrypt`?

I mean, is that part of your code compatible with the official  IO.HK sources?

**Comment by ilap** [comment]
Nope, check the [relevant haskell code](https://github.com/input-output-hk/cardano-sl/blob/develop/crypto/Pos/Crypto/Signing/Safe.hs#L85) which simply calls the functuon above /w the scrypted passphrase.

**Comment by bazooka70** [comment]
Thanks. I guess your "Nope" refers to my 

> is the cryptonite_fastpbkdf2_hmac_sha512 implemented via Scrypt?

And your code **is** compatible. Am I right? :)
